name: Test Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      MESSAGE:
        description: "Message to echo"
        required: true
        default: "info"
        type: choice
        options:
          - info
          - warning
          - debug        
      USER_NAME:
        description: "User's name"
        required: false
      ENVIRONMENT:
        description: "Deployment environment"
        required: true
        default: "development"
        type: choice
        options:
          - info
          - warning
          - debug        

jobs:
  echo-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print MESSAGE
        run: echo "Message ${{ inputs.MESSAGE }}"
      - name: Print USER_NAME
        run: echo "User Name ${{ inputs.USER_NAME }}"
      - name: Print ENVIRONMENT
        run: echo "Environment ${{ inputs.ENVIRONMENT }}"
